### ISSUE TITLE
Disabling "move cursor to original location after release" crashes the game.

### ISSUE THREAD

**Issue by Ghostkat9** [Friendly0Fire/GW2Radial#269]
This was a previous issue (#247) that is still persisting. I don't quite understand why it was closed. It used to be that turning it off made the game much easier to play while in action camera mode, especially for those of us who prefer to play on a controller and not lose where our cursors were when we needed to exit action camera for clicking things. With this continuously causing crashes, it makes the radial menu very annoying to use.

I saw void-method was writing about a fix but I don't understand the code, how to implement it or if it even works. Will that fix be implemented in the next version?

**Comment by MarvIcNet** [comment]
### I can also say that disabling the option "move cursor to original location after release" crash the game for me.

**How to reproduce the bug:**
1) Unchek the option "move cursor to original location after release".
Check the option "Reset cursor to center with Center Locked Keybind".
![Radial bug - uncheck option move cursor to original location after release](https://user-images.githubusercontent.com/17121309/149661578-a809be52-421c-48e9-95d4-c73ae77340ba.PNG)

2) Clic on your GW2radial key bind and dont move the mouse (let it in the circle).
Then release your GW2radial key bind.
![Radial bug - let the mouse inside the center](https://user-images.githubusercontent.com/17121309/149661639-5fc92f25-b29d-485b-92e3-654e1a8d79eb.PNG)


3) The game crash
![Radial bug - error](https://user-images.githubusercontent.com/17121309/149661760-e09e5053-9b6e-4b07-ae35-92dad81833bf.PNG)

I can reproduce this bug 100% of the time.
If you don't have the same option as me, the most important is to uncheck the option "move cursor to original location after release" and then release your GW2radial key bind inside the center of the radial (no monts selected).

Thank you so much for your work FirendlyOFire.

**Comment by Friendly0Fire** [comment]
> I don't quite understand why it was closed.

It was closed because it's been resolved in a commit. Please don't reopen the issue and wait for the update to come out or grab a nightly.

**Comment by Ghostkat9** [comment]
I don't understand what that means, which is why I reopened it. What do you
mean, "it was resolved in a commit?" I explained in my post, I didn't
understand how to implement that fix or if if even worked. The only thing
it showed was that you closed the issue without further communication.

So no, it's not resolved until you implement the fix in an update. Please
read my post in its entirety before replying like this, because your
response isn't helpful or constructive.

**Comment by Ghostkat9** [comment]
I don't understand what "grab a nightly" means, either. English, please?
Not everyone who uses your add-on and reports bugs here speaks Github.

**Comment by Friendly0Fire** [comment]
Sorry, I really don't have the time to teach you how Github works. *Wait for the update.*

**Comment by Ghostkat9** [comment]
Or, you can learn to be a better communicator. You could have just said
"it's being worked on" and left it at that. If you're going to be a snide
jerk about it and ignore when the poster outright says they saw you closed
it without communication, and not effectively communicate in response
because you don't seem to understand not everyone lives on this platform
like you do, people will go elsewhere due to your attitude alone.

I don't have the time to teach you basic communication etiquette or
manners, sorry. I'll go use a different radial mount add-on instead. Best
of luck to everyone who has to put up with your nasty temperament.

**Comment by Friendly0Fire** [comment]
I'm a developer, not a community manager, and I'm doing this in my very limited free time. This process of auto-closing issues is standard practice and you're literally the first person to complain about it. You can Google how Github works, there's tons of documentations on that. By interacting with this website, you're expected to understand the basics of what Github is, and words like "commit" and "nightly" are pretty standard fare.

Every time I have to explain something (and you are not the first requesting special treatment), I lose time I could've put on the addon and lose interest in continuing my work.

> I'll go use a different radial mount add-on instead.

Oh please do, they're a dime a dozen I'm sure.

**Comment by Ghostkat9** [comment]
Being a developer also means you need to have interpersonal skills to
communicate with others, especially in a team environment. If you choose to
do this as a service to a community, you naturally open yourself up to
having to communicate with others.

We are taking our time as well to provide you with detailed, actionable
feedback, like the post MarvIcNet made above. You do this on your own time?
Good for you. He put together screenshots and details on how to reproduce
an issue for your awareness. You don't think he has things he would rather
be doing with his time? We are all volunteering here to QA test for you,
FOR FREE. Without our feedback, you wouldn't be aware of half the bugs your
overlay has, so show some respect. It's not just YOUR leisure time going
into this.

Being a developer and not being a community manager doesn't abrogate you
from the need to have basic social skills, nor does it excuse the nastiness
of your temperament. I've given feedback to plenty of add-on developers who
do this on their own time, and this is the first time I've ever seen one
who had the gall to say something like "I don't have time to teach you
Github" in response to being confused when communication wasn't
straightforward, and then say something ludicrous like "I'm a developer,
not a community manager" like that somehow gives you a pass.

It also isn't the first time you're getting this, and I'm not the first
person to tell you, either. I know because when you disappeared for months
while the overlay was still in alpha, people were here raising issues about
bugs and other things. I know because I was replying to them, assuming you
had outright abandoned GW2Radial to work on Warframe mods, and went to use
another instead. They may be a dime a dozen, sure, but they still exist,
and their developers are more pleasant and don't make excuses for poor
behavioural conduct.

If wasted time is your concern, then you should learn to communicate better
up-front so a back-and-forth isn't necessary. "It's being worked on" is
four words and I would've gotten the message. Instead, you avoid
communication, and are investing time writing shitposting replies, when I'm
pretty sure I made it clear I was going elsewhere because I didn't want to
deal with your nasty attitude. That didn't necessitate a response, and you
could have left it alone. You're just picking a fight on the internet at
this point.

At this point I'd actually rather you get totally demoralized and abandon
GW2Radial. I don't want to give positive reinforcement to stroke the ego of
such a poor personality. With everything you are doing being unofficial and
open-source, and there being plenty of other overlay developers for this
game, someone is bound to step in and pick up the torch, hopefully someone
with more respect for the time and effort we take to provide unpaid quality
assurance testing for them and has more pleasant interpersonal
communication skills.

**Comment by Friendly0Fire** [comment]
K.
